name: ACCESS SERVER 
run-name: connecting to AWS !!!
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: 13.127.191.140
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: echo hello world > hello.txt
