name: ACCESS SERVER 
run-name: connecting to AWS !!!
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - shell: bash
         env:
            SUPER_SECRET: ${{ secrets.SECRET }}
            HOST: ${{ secrets.HOSTNAME }}
         run: |
            echo "$SUPER_SECRET"
            echo "$HOST"

