name: pehla action
run-name: ${{ github.actor }} is doing actionsss !!
on: [push]
jobs:
  checkingggg-version:
    runs-on: ubuntu-latest
    steps:
      - run: docker ps -a
      - run: docker images
      - run: docker volume ls
      - run: docker network ls
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
