name: pehla action
run-name: ${{ github.actor }} is doing actionsss !!
on: [push]
jobs:
  checkingggg-version:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
