name: pehla action
run-name: ${{ github.actor }} is doing actionsss !!
on: [push]
jobs:
  checkingggg-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hehe"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
